<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [1]:
import numpy as np



# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [13]:
array_uni = np.array(range (0,10))
print (array_uni)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [ ]:
np.transpose

In [25]:
array_uni.reshape(2,5)



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [26]:
np.where(array_uni != 0)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [54]:
array_3_0 = np.random.randint(0,2,(3,3))
print (array_3_0)

[[0 1 1]
 [0 0 0]
 [0 0 1]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [57]:
array_u_aleatorio = np.random.randint(1,100,10)
print(np.max(array_u_aleatorio))
print(np.min(array_u_aleatorio))

98
24


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [64]:
unadim = np.random.randint (1,100,1)
print(unadim)
np.transpose(unadim)


[72]


array([72])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [84]:
array_tri = np.random.randint(1,25,(2,3,4))
print(f"El array es: \n {array_tri}")
print (array_tri [array_tri == 15][0]) 
print (f"todos los del primer array: \n{array_tri [0]}")
print (f"ultima fila del ultimo array: \n{array_tri [1,2]}")

El array es: 
 [[[15 24 22  6]
  [17 18  2  1]
  [10 11 15  2]]

 [[12  9  4  6]
  [21 16 16 17]
  [ 8 18 12 20]]]
15
todos los del primer array: 
[[15 24 22  6]
 [17 18  2  1]
 [10 11 15  2]]
ultima fila del ultimo array: 
[ 8 18 12 20]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [115]:
array_r = np.random.randint(1,24,(4,3,2))
print (array_r)
print (f"{array_r [1,1]}")
array_r [1,1] = np.zeros_like(array_r [1,1])
print(f"{np.zeros_like(array_r [1,1])}")

array_r [0] = np.ones_like(array_r[-1:] *-1)
print(array_r)


[[[21  3]
  [18 23]
  [ 6 13]]

 [[ 2  6]
  [20 11]
  [ 7  7]]

 [[ 2 23]
  [ 9  2]
  [ 5 21]]

 [[19 23]
  [10 10]
  [11  3]]]
[20 11]
[0 0]
[[[ 1  1]
  [ 1  1]
  [ 1  1]]

 [[ 2  6]
  [ 0  0]
  [ 7  7]]

 [[ 2 23]
  [ 9  2]
  [ 5 21]]

 [[19 23]
  [10 10]
  [11  3]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [147]:
array_f = np.random.randint(-10,13,(4,3,2))
mayor_5 = (array_f[array_f > 5])
print (mayor_5)

array_f[array_f < 0] = 0

print (array_f)




[ 8 12  6 10  6 10 12  6]
[[[ 8  0]
  [ 5  0]
  [ 0  0]]

 [[12  2]
  [ 0  0]
  [ 0  0]]

 [[ 6 10]
  [ 6  4]
  [ 0 10]]

 [[12  0]
  [ 0  6]
  [ 0  0]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [181]:
array_g = np.random.randint(1,27,(3,3,3))
print (array_g)
print (f"\n {array_g[1,:,1:3]}")
print (f"\n {np.array(array_g[-1][array_g[-1] > 20])}")

[[[ 5 25  8]
  [21  4 21]
  [15 18 23]]

 [[ 1  5 16]
  [18 17  5]
  [14 19  1]]

 [[11  1 14]
  [26 10 15]
  [ 5  9  6]]]

 [[ 5 16]
 [17  5]
 [19  1]]

 [26]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [184]:
array_u_aleatorio = np.random.randint(1,100,10)
print(f"\n{array_u_aleatorio}\n")
max_condition = array_u_aleatorio == np.max(array_u_aleatorio) 
min_condition = array_u_aleatorio == np.min(array_u_aleatorio)

array_u_aleatorio[max_condition] = 0
array_u_aleatorio[min_condition] = 0

print(array_u_aleatorio)


[67  3  9 72 46 87 25 29 96  4]

[67  0  9 72 46 87 25 29  0  4]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [185]:
array_15_aleatorio = np.random.randint(1,100,10)
array_ordenado = np.sort(array_15_aleatorio)

print(array_ordenado)

[ 6 15 46 49 51 52 60 79 80 94]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [190]:
matriz_4x4 = np.random.randint(1,100,(4,4))
matriz_sumada = np.sum(matriz_4x4,axis = 0)

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [202]:
matriz_5x5 =  np.zeros((5,5))
matriz_5x5[0, :] = 1    
matriz_5x5[-1, :] = 1     
matriz_5x5[:, 0] = 1      
matriz_5x5[:, -1] = 1 


print(matriz_5x5)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [205]:
media = np.mean(array_u_aleatorio)
desv = np.std(array_u_aleatorio)


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [216]:
array_14 = np.random.randint(1,24,(2,3,4))

array_14_traspuesto = array_14.transpose(2,1,0)
print(f"\n {array_14}")
print(f"\n{array_14_traspuesto}")



 [[[ 5 20 12 23]
  [19 14  8  3]
  [19  9 13  2]]

 [[17  9  5  2]
  [12  1 20 21]
  [ 1  7 19 13]]]

[[[ 5 17]
  [19 12]
  [19  1]]

 [[20  9]
  [14  1]
  [ 9  7]]

 [[12  5]
  [ 8 20]
  [13 19]]

 [[23  2]
  [ 3 21]
  [ 2 13]]]


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [218]:
array_15 = np.random.randint(1,24,(3,4,2))
array_15_traspuesto = array_15.transpose(1,0,2)

print(f"\n {array_15}")
print(f"\n {array_15_traspuesto}")


 [[[ 3  8]
  [ 8 16]
  [12  8]
  [17 13]]

 [[13 16]
  [ 8  1]
  [22  5]
  [ 9 20]]

 [[12 18]
  [ 1 16]
  [ 6  6]
  [ 6 10]]]

 [[[ 3  8]
  [13 16]
  [12 18]]

 [[ 8 16]
  [ 8  1]
  [ 1 16]]

 [[12  8]
  [22  5]
  [ 6  6]]

 [[17 13]
  [ 9 20]
  [ 6 10]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [220]:
array_16 = np.random.randint(1,24,(3,2,4))
array_16_traspuesto = array_16.transpose(2,0,1)

print(f"\n {array_16}")
print(f"\n {array_16_traspuesto}")


 [[[ 1 12 15  7]
  [17  7  2 14]]

 [[17  5  3  4]
  [12 19 14 11]]

 [[ 1 15 14 15]
  [ 8 20 14  4]]]

 [[[ 1 17]
  [17 12]
  [ 1  8]]

 [[12  7]
  [ 5 19]
  [15 20]]

 [[15  2]
  [ 3 14]
  [14 14]]

 [[ 7 14]
  [ 4 11]
  [15  4]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.